package snapshot

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5"
)

type legacySpec struct {
	definition AggregateDefinition
	query      string
}

const globalHoneyCTE = `
WITH global_honey AS (
 SELECT
  (SELECT COALESCE(SUM(session_lbs), 0) FROM (
    SELECT COALESCE(NULLIF(hs.total_extracted_weight, 0),
      (SELECT COALESCE(SUM(hh.calculated_honey_weight), 0)
       FROM honey_harvests hh
       WHERE hh.session_id = hs.id AND hh.deleted_at IS NULL)) AS session_lbs
    FROM harvest_sessions hs) sessions)
  + (SELECT COALESCE(SUM(calculated_honey_weight), 0)
     FROM honey_harvests WHERE session_id IS NULL AND deleted_at IS NULL) AS total_harvested_lbs,
  COALESCE((SELECT SUM(amount_lbs) FROM honey_movements WHERE kind='jarring'), 0) AS jarred_lbs,
  COALESCE((SELECT SUM(amount_lbs) FROM honey_movements WHERE kind='bulk_use'), 0) AS bulk_used_lbs,
  COALESCE((SELECT SUM(amount_lbs) FROM honey_movements WHERE kind='loss'), 0) AS loss_lbs
)`

func legacySpecs(currency string) []legacySpec {
	def := func(name, version, description, unit string, dimensions, statuses []string, sign string) AggregateDefinition {
		return AggregateDefinition{Name: name, Version: version, Description: description,
			Statuses: statuses, Dimensions: dimensions, Unit: unit, Rounding: "no aggregate rounding; canonical fixed-decimal JSON; UI-only displays may round",
			SignConvention: sign, QueryVersion: LegacyAggregateFamily}
	}
	return []legacySpec{
		{def("global_bulk_honey", "legacy-honey-bulk-v1", "Current honeyBulkOnHand formula: session true-up when nonzero, otherwise live harvest entries; plus live sessionless harvests; minus all jarring, bulk_use, and loss movement pounds.", "lb", nil, []string{"honey_harvests.deleted_at IS NULL"}, "movement amount_lbs is stored positive for jarring/bulk_use/loss; each category is subtracted; reversal rows are negative"), globalHoneyCTE + ` SELECT to_jsonb(q) FROM (SELECT *, total_harvested_lbs-jarred_lbs-bulk_used_lbs-loss_lbs AS bulk_on_hand_lbs FROM global_honey) q`},
		{def("lot_bulk_honey", "legacy-honey-lot-view-v1", "Exact honey_lot_balances view projection: lot ceiling minus attributed jarring, bulk_use, and loss.", "lb", []string{"lot_id", "varietal_id"}, nil, "positive draws are subtracted; negative reversal draws add back"), `SELECT COALESCE(jsonb_agg(to_jsonb(q) ORDER BY lot_id), '[]'::jsonb) FROM (SELECT * FROM honey_lot_balances) q`},
		{def("varietal_bulk_honey", "legacy-honey-varietal-view-v1", "Exact honey_varietal_balances rollup over honey_lot_balances.", "lb", []string{"varietal_id"}, nil, "lot draw signs are inherited from honey_lot_balances"), `SELECT COALESCE(jsonb_agg(to_jsonb(q) ORDER BY varietal_id), '[]'::jsonb) FROM (SELECT * FROM honey_varietal_balances) q`},
		{def("unassigned_bulk_honey_residual", "legacy-honey-unassigned-residual-v1", "Unmaterialized 00047 residual: total harvested minus lot ceilings minus jarring/bulk_use/loss movements whose lot_id is null.", "lb", []string{"bucket=unassigned"}, []string{"honey_harvests.deleted_at IS NULL"}, "unassigned positive draws subtract; negative reversals add back"), globalHoneyCTE + ` SELECT to_jsonb(q) FROM (SELECT total_harvested_lbs - COALESCE((SELECT SUM(honey_weight_lbs) FROM harvest_lots),0) - COALESCE((SELECT SUM(amount_lbs) FROM honey_movements WHERE lot_id IS NULL AND kind IN ('jarring','bulk_use','loss')),0) AS on_hand_lbs FROM global_honey) q`},
		{def("harvest_lot_mutable_ceiling", "legacy-harvest-lot-ceiling-v1", "Current bottling ceiling is harvest_lots.honey_weight_lbs; honey_weight_source declares manual versus derived and linked live harvest pounds expose the derivation input.", "lb", []string{"lot_id", "honey_weight_source"}, []string{"linked honey_harvests.deleted_at IS NULL"}, "weights are nonnegative supply ceilings"), `SELECT COALESCE(jsonb_agg(to_jsonb(q) ORDER BY lot_id), '[]'::jsonb) FROM (SELECT l.id AS lot_id,l.honey_weight_lbs,l.honey_weight_source,COALESCE(SUM(h.calculated_honey_weight) FILTER (WHERE h.deleted_at IS NULL),0) AS linked_live_harvest_lbs FROM harvest_lots l LEFT JOIN harvest_lot_harvests link ON link.lot_id=l.id LEFT JOIN honey_harvests h ON h.id=link.harvest_id GROUP BY l.id,l.honey_weight_lbs,l.honey_weight_source) q`},
		{def("finished_jar_inventory", "legacy-jar-inventory-v1", "Current jar formula: jarring + jar_adjustment - non-cancelled jar sales - give_away, including inactive sizes only while their balance is nonzero.", "count", []string{"jar_size_id"}, []string{"sales.order_status <> cancelled", "jar_sizes.is_active OR on_hand <> 0"}, "jarring and signed adjustments add; sales and give_away subtract; reversal movements carry negative quantities"), `SELECT COALESCE(jsonb_agg(to_jsonb(q) ORDER BY sort_order,label), '[]'::jsonb) FROM (SELECT js.id AS jar_size_id,js.label,js.sort_order,COALESCE(m.jarred,0) AS jarred,COALESCE(si.sold,0) AS sold,COALESCE(m.given_away,0) AS given_away,COALESCE(m.adjusted,0) AS adjusted,COALESCE(m.jarred,0)+COALESCE(m.adjusted,0)-COALESCE(si.sold,0)-COALESCE(m.given_away,0) AS on_hand FROM jar_sizes js LEFT JOIN (SELECT jar_size_id,SUM(quantity) FILTER (WHERE kind='jarring') AS jarred,SUM(quantity) FILTER (WHERE kind='give_away') AS given_away,SUM(quantity) FILTER (WHERE kind='jar_adjustment') AS adjusted FROM honey_movements GROUP BY jar_size_id) m ON m.jar_size_id=js.id LEFT JOIN (SELECT si.jar_size_id,SUM(si.quantity) AS sold FROM sale_items si JOIN sales s ON s.id=si.sale_id WHERE s.order_status<>'cancelled' AND si.kind='jar' GROUP BY si.jar_size_id) si ON si.jar_size_id=js.id WHERE js.is_active OR COALESCE(m.jarred,0)+COALESCE(m.adjusted,0)-COALESCE(si.sold,0)-COALESCE(m.given_away,0)<>0) q`},
		{def("catalog_product_inventory", "legacy-product-inventory-v1", "Current SKU formula: quantity_out from non-voided batches + live signed product adjustments - product sale lines on non-cancelled sales.", "count", []string{"product_id", "kind"}, []string{"product_batches.voided_at IS NULL", "product_adjustments.deleted_at IS NULL", "sales.order_status <> cancelled"}, "batch output and positive adjustments add; sales and negative adjustments subtract"), `SELECT COALESCE(jsonb_agg(to_jsonb(q) ORDER BY kind,name,size_label NULLS FIRST), '[]'::jsonb) FROM (SELECT p.id AS product_id,p.name,p.kind,p.size_label,COALESCE(b.made,0) AS made,COALESCE(s.sold,0) AS sold,COALESCE(a.adjusted,0) AS adjusted,COALESCE(b.made,0)+COALESCE(a.adjusted,0)-COALESCE(s.sold,0) AS on_hand FROM product_catalog p LEFT JOIN (SELECT product_id,SUM(quantity_out) AS made FROM product_batches WHERE voided_at IS NULL GROUP BY product_id)b ON b.product_id=p.id LEFT JOIN (SELECT si.product_id,SUM(si.quantity) AS sold FROM sale_items si JOIN sales sale ON sale.id=si.sale_id WHERE sale.order_status<>'cancelled' AND si.product_id IS NOT NULL GROUP BY si.product_id)s ON s.product_id=p.id LEFT JOIN (SELECT product_id,SUM(delta) AS adjusted FROM product_adjustments WHERE deleted_at IS NULL GROUP BY product_id)a ON a.product_id=p.id) q`},
		{def("raw_propolis_inventory", "legacy-propolis-grams-v1", "Current propolis formula: live harvest grams (ounces x 28.349523125) minus non-voided tincture batch consumption minus non-cancelled propolis sale quantity x catalog net_grams.", "g", nil, []string{"propolis_harvests.deleted_at IS NULL", "product_batches.kind=tincture AND voided_at IS NULL", "sale_items.kind=propolis AND sales.order_status <> cancelled"}, "harvest adds; tincture inputs and raw propolis sales subtract"), `SELECT to_jsonb(q) FROM (SELECT harvested_grams,consumed_grams,sold_grams,harvested_grams-consumed_grams-sold_grams AS on_hand_grams FROM (SELECT COALESCE((SELECT SUM(CASE WHEN unit='ounces' THEN amount*28.349523125 ELSE amount END) FROM propolis_harvests WHERE deleted_at IS NULL),0) AS harvested_grams,COALESCE((SELECT SUM(CASE WHEN propolis_unit='ounces' THEN propolis_amount*28.349523125 ELSE propolis_amount END) FROM product_batches WHERE kind='tincture' AND voided_at IS NULL),0) AS consumed_grams,COALESCE((SELECT SUM(si.quantity*p.net_grams) FROM sale_items si JOIN sales sale ON sale.id=si.sale_id JOIN product_catalog p ON p.id=si.product_id WHERE si.kind='propolis' AND p.net_grams IS NOT NULL AND sale.order_status<>'cancelled'),0) AS sold_grams) totals) q`},
		{def("away_finished_goods", "legacy-stock-away-v1", "Exact stockAwayQuantities formula: stock movement sums plus negative non-cancelled, location-scoped sale lines, excluding the home location.", "count", []string{"location_id", "jar_size_id|product_id"}, []string{"sales.order_status <> cancelled", "stock_locations.is_home=false"}, "movement quantity is signed; sale quantities are negated"), `SELECT COALESCE(jsonb_agg(to_jsonb(q) ORDER BY location_id,jar_size_id NULLS LAST,product_id NULLS LAST), '[]'::jsonb) FROM (SELECT location_id,jar_size_id,product_id,SUM(qty)::int AS on_hand FROM (SELECT m.location_id,m.jar_size_id,m.product_id,m.quantity AS qty FROM stock_movements m UNION ALL SELECT s.stock_location_id,si.jar_size_id,si.product_id,-si.quantity FROM sale_items si JOIN sales s ON s.id=si.sale_id WHERE s.order_status<>'cancelled' AND s.stock_location_id IS NOT NULL AND (si.jar_size_id IS NOT NULL OR si.product_id IS NOT NULL)) movements WHERE location_id NOT IN (SELECT id FROM stock_locations WHERE is_home) GROUP BY 1,2,3 HAVING SUM(qty)<>0) q`},
		{def("home_jar_residual", "legacy-home-jar-residual-v1", "Home jars are the global finished-jar balance minus the sum of every away location balance for the jar size.", "count", []string{"jar_size_id", "location=home"}, []string{"same filters as finished_jar_inventory and away_finished_goods"}, "away positive stock subtracts from global; negative away stock adds to residual"), `WITH global AS (SELECT js.id AS jar_size_id,COALESCE(m.jarred,0)+COALESCE(m.adjusted,0)-COALESCE(si.sold,0)-COALESCE(m.given_away,0) AS qty FROM jar_sizes js LEFT JOIN (SELECT jar_size_id,SUM(quantity) FILTER(WHERE kind='jarring') jarred,SUM(quantity) FILTER(WHERE kind='give_away') given_away,SUM(quantity) FILTER(WHERE kind='jar_adjustment') adjusted FROM honey_movements GROUP BY jar_size_id)m ON m.jar_size_id=js.id LEFT JOIN (SELECT si.jar_size_id,SUM(si.quantity) sold FROM sale_items si JOIN sales s ON s.id=si.sale_id WHERE s.order_status<>'cancelled' AND si.kind='jar' GROUP BY si.jar_size_id)si ON si.jar_size_id=js.id), away AS (SELECT jar_size_id,SUM(qty) qty FROM (SELECT m.location_id,m.jar_size_id,m.quantity qty FROM stock_movements m WHERE m.jar_size_id IS NOT NULL UNION ALL SELECT s.stock_location_id,si.jar_size_id,-si.quantity FROM sale_items si JOIN sales s ON s.id=si.sale_id WHERE s.order_status<>'cancelled' AND s.stock_location_id IS NOT NULL AND si.jar_size_id IS NOT NULL)x WHERE location_id NOT IN(SELECT id FROM stock_locations WHERE is_home) GROUP BY jar_size_id) SELECT COALESCE(jsonb_agg(jsonb_build_object('jar_size_id',g.jar_size_id,'on_hand',g.qty-COALESCE(a.qty,0)) ORDER BY g.jar_size_id),'[]'::jsonb) FROM global g LEFT JOIN away a USING(jar_size_id)`},
		{def("home_product_residual", "legacy-home-product-residual-v1", "Home catalog products are the global live batch + adjustment - sale balance minus the sum of every away location balance.", "count", []string{"product_id", "location=home"}, []string{"same filters as catalog_product_inventory and away_finished_goods"}, "away positive stock subtracts from global; negative away stock adds to residual"), `WITH global AS (SELECT p.id product_id,COALESCE(b.made,0)+COALESCE(a.adjusted,0)-COALESCE(s.sold,0) qty FROM product_catalog p LEFT JOIN(SELECT product_id,SUM(quantity_out) made FROM product_batches WHERE voided_at IS NULL GROUP BY product_id)b ON b.product_id=p.id LEFT JOIN(SELECT product_id,SUM(delta) adjusted FROM product_adjustments WHERE deleted_at IS NULL GROUP BY product_id)a ON a.product_id=p.id LEFT JOIN(SELECT si.product_id,SUM(si.quantity) sold FROM sale_items si JOIN sales sale ON sale.id=si.sale_id WHERE sale.order_status<>'cancelled' AND si.product_id IS NOT NULL GROUP BY si.product_id)s ON s.product_id=p.id),away AS (SELECT product_id,SUM(qty) qty FROM(SELECT m.location_id,m.product_id,m.quantity qty FROM stock_movements m WHERE m.product_id IS NOT NULL UNION ALL SELECT s.stock_location_id,si.product_id,-si.quantity FROM sale_items si JOIN sales s ON s.id=si.sale_id WHERE s.order_status<>'cancelled' AND s.stock_location_id IS NOT NULL AND si.product_id IS NOT NULL)x WHERE location_id NOT IN(SELECT id FROM stock_locations WHERE is_home) GROUP BY product_id) SELECT COALESCE(jsonb_agg(jsonb_build_object('product_id',g.product_id,'on_hand',g.qty-COALESCE(a.qty,0)) ORDER BY g.product_id),'[]'::jsonb) FROM global g LEFT JOIN away a USING(product_id)`},
		{def("equipment_stock_status", "legacy-equipment-status-view-v1", "Exact equipment_stock_status view: mutable guarded totals and conditions, deployed=sum(quantity-quantity_returned), available=total_owned-damaged-retired-deployed.", "count", []string{"stock_id", "type_id"}, nil, "deployments/damaged/retired subtract from owned; returned quantity reduces deployed"), `SELECT COALESCE(jsonb_agg(to_jsonb(q) ORDER BY stock_id),'[]'::jsonb) FROM (SELECT * FROM equipment_stock_status) q`},
		{def("equipment_ledger_reconciliation", "legacy-equipment-reconciliation-view-v1", "Exact equipment_stock_reconciliation view comparing trigger-guarded mutable columns with adjustment/state ledgers.", "count", []string{"stock_id"}, nil, "signed ownership adjustments; state transitions add/subtract damaged and retired ledgers"), `SELECT COALESCE(jsonb_agg(to_jsonb(q) ORDER BY stock_id),'[]'::jsonb) FROM (SELECT * FROM equipment_stock_reconciliation) q`},
		{def("equipment_condition_totals", "legacy-equipment-condition-columns-v1", "Condition quantities are the equipment_stock damaged_quantity and retired_quantity columns guarded by migration-00006 triggers.", "count", []string{"stock_id", "condition"}, nil, "serviceable=total_owned-damaged-retired; condition columns are nonnegative"), `SELECT COALESCE(jsonb_agg(jsonb_build_object('stock_id',id,'total_owned',total_owned,'damaged',damaged_quantity,'retired',retired_quantity,'serviceable',total_owned-damaged_quantity-retired_quantity) ORDER BY id),'[]'::jsonb) FROM equipment_stock`},
		{def("packaging_equipment_inventory", "legacy-packaging-equipment-v1", "Migration 00048 packaging is the equipment ledger subset whose equipment type category is packaging; availability remains equipment_stock_status.available.", "count", []string{"stock_id", "type_id", "category=packaging"}, nil, "same signs as equipment_stock_status; consumed adjustments are negative"), `SELECT COALESCE(jsonb_agg(to_jsonb(q) ORDER BY stock_id),'[]'::jsonb) FROM (SELECT * FROM equipment_stock_status WHERE type_category='packaging') q`},
		{def("equipment_bom_components", "legacy-equipment-bom-v1", "Migration 00046 BOM quantities plus current component availability; assembly consumes quantity*line.quantity and produces parent quantity through ordinary equipment adjustments.", "count", []string{"parent_type_id", "component_type_id"}, nil, "component requirements are positive; assembled/disassembled adjustment signs determine stock"), `SELECT COALESCE(jsonb_agg(to_jsonb(q) ORDER BY parent_type_id,component_type_id),'[]'::jsonb) FROM (SELECT c.parent_type_id,c.component_type_id,c.quantity,s.available AS component_available FROM equipment_type_components c LEFT JOIN equipment_stock_status s ON s.type_id=c.component_type_id) q`},
		{def("sales_financial_totals", "legacy-sales-financial-v1", "Financial totals grouped by sales order_status using stored integer cents; cancelled remains a separate status and is not silently removed.", "cent", []string{"currency", "order_status"}, []string{"draft", "pending", "paid", "fulfilled", "cancelled"}, "stored invoice/tax/discount/paid amounts are nonnegative cents"), `SELECT COALESCE(jsonb_agg(to_jsonb(q) ORDER BY order_status),'[]'::jsonb) FROM (SELECT '` + currency + `'::text currency,order_status,COUNT(*) record_count,SUM(total_amount_cents) total_amount_cents,SUM(discount_amount_cents) discount_amount_cents,SUM(tax_cents) tax_cents,SUM(amount_paid_cents) amount_paid_cents FROM sales GROUP BY order_status) q`},
		{def("expense_financial_totals", "legacy-expense-financial-v1", "Expense totals grouped by category using stored integer cents.", "cent", []string{"currency", "category"}, nil, "expense amounts are positive costs"), `SELECT COALESCE(jsonb_agg(to_jsonb(q) ORDER BY category),'[]'::jsonb) FROM (SELECT '` + currency + `'::text currency,category,COUNT(*) record_count,SUM(amount_cents) amount_cents FROM expenses GROUP BY category) q`},
		{def("production_batch_totals", "legacy-production-batches-v1", "Production output from non-voided product batches, grouped by product and kind.", "declared product unit", []string{"product_id", "kind"}, []string{"product_batches.voided_at IS NULL"}, "quantity_out is positive produced units"), `SELECT COALESCE(jsonb_agg(to_jsonb(q) ORDER BY product_id,kind),'[]'::jsonb) FROM (SELECT product_id,kind,COUNT(*) batch_count,SUM(quantity_out) quantity_out FROM product_batches WHERE voided_at IS NULL GROUP BY product_id,kind) q`},
	}
}

func computeLegacyAggregates(ctx context.Context, tx pgx.Tx, currency string) ([]AggregateDefinition, error) {
	specs := legacySpecs(currency)
	out := make([]AggregateDefinition, 0, len(specs))
	for _, spec := range specs {
		var raw []byte
		if err := tx.QueryRow(ctx, spec.query).Scan(&raw); err != nil {
			return nil, fmt.Errorf("aggregate %s: %w", spec.definition.Name, err)
		}
		canonical, err := CanonicalJSON(raw)
		if err != nil {
			return nil, fmt.Errorf("aggregate %s canonicalize: %w", spec.definition.Name, err)
		}
		spec.definition.Value = json.RawMessage(canonical)
		out = append(out, spec.definition)
	}
	return out, nil
}

func newLedgerFamily() AggregateFamily {
	null := json.RawMessage("null")
	return AggregateFamily{Label: "new-ledger definitions", Version: NewAggregateFamily,
		Definitions: []AggregateDefinition{{
			Name: "inventory_on_hand", Version: "new-ledger-inventory-v1", Description: "Reserved Wave-2 target: immutable signed movement sum by item, location, lot, and condition.",
			Dimensions: []string{"item_id", "location_id", "lot_id", "condition"}, Unit: "inventory_items.canonical_unit", Rounding: "per inventory item numeric policy", SignConvention: "receipts positive; issues negative; corrections are reversal plus replacement", QueryVersion: NewAggregateFamily, Value: null,
		}},
		Mapping: []AggregateMapping{
			{LegacyName: "unassigned_bulk_honey_residual", NewLedgerName: "inventory_on_hand", Transform: "create a classified opening-balance operation for the unassigned bulk virtual lot/location; preserve the exact legacy residual", TransformVer: "legacy-residual-split-v1"},
			{LegacyName: "home_jar_residual", NewLedgerName: "inventory_on_hand", Transform: "create per-jar-item opening balances at home equal to global balance minus all non-home balances", TransformVer: "legacy-residual-split-v1"},
			{LegacyName: "home_product_residual", NewLedgerName: "inventory_on_hand", Transform: "create per-product-item opening balances at home equal to global balance minus all non-home balances", TransformVer: "legacy-residual-split-v1"},
		},
	}
}
